title: Why planes are awesome
author: Jean-Michel NOKAYA
email: nokaya.jeanmichel@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A site about planes. Training for Github site.

# social links
#twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  Khedoth # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
